# -*- coding: utf-8 -*-
"""Master data kategori, sub kategori, dan daftar produk AGR.ID"""

# Kategori utama marketplace
KATEGORI = ["Pertanian", "Perkebunan", "Perikanan", "Peternakan"]

TIPE_PENJUAL = ["Perorangan", "Koperasi", "Kelompok Tani (Paguyuban)"]
TIPE_PEMBELI = ["Perorangan", "Corporate"]

# Sub kategori + daftar produk & jenisnya per kategori
MASTER_PRODUK = {
    "Pertanian": {
        "subkategori": ["Sayuran", "Buah-buahan"],
        "produk": {
            "Sayuran": [
                ("Cabai Merah", ["Biasa", "Keriting", "Rawit/Teri"]),
                ("Bawang Merah", ["Lokal", "Philips", "Shallot"]),
                ("Bawang Putih", ["Bonggol", "Umbi Kuning", "Umbi Putih"]),
                ("Kentang", ["Granola", "Atlantik", "Kentang Lokal"]),
                ("Wortel", ["Lokal", "Impor", "Wortel Ungu"]),
                ("Tomat", ["Buah Besar", "Cherry", "Tomat Hidroponik", "Lokal"]),
                ("Kangkung", ["Lokal", "Hidroponik", "Cina"]),
                ("Bayam", ["Local", "Cina/Hijau Besar", "Merah", "Hidroponik"]),
                ("Selada", ["Salad Lokan", "Romaine", "Iceberg", "Hidroponik"]),
                ("Kol / Kubis", ["Putih", "Ungu", "Savoy"]),
                ("Brokoli", ["Lokal", "Hidroponik", "Organik"]),
                ("Kembang Kol", ["Lokal", "Impor"]),
                ("Terong", ["Ungu", "Green/Egg", "Lalat/Capelin"]),
                ("Timun", ["Lokal", "Hidroponik", "Japan/Cucumber"]),
                ("Labu Siamu / Labu Air", ["Lokal"]),
                ("Pare / Pare Jawa", ["Lokal", "Hybrid"]),
                ("Buncis", ["Buncis Muda", "Buncis Jepang/Snow Pea"]),
                ("Kacang Panjang", ["Lokal", "Ungu"]),
                ("Seledri", ["Lokal", "Hidroponik"]),
                ("Daun Bawang / Daung Kucai", ["Lokal"]),
                ("Bit", ["Bit Merah", "Organik"]),
                ("Lobak", ["Radish Jepang", "Lobak Lokal"]),
                ("Jagung Manis", ["Pipilan", "Tongkol", "Baby Corn"]),
                ("Jamur Tiram", ["Segar", "Kering"]),
                ("Jamur Shiitake", ["Segar", "Kering"]),
                ("Jamur Kuping", ["Segar", "Kering"]),
                ("Jahe", ["Emprit", "Gajah", "Merah/Ahath"]),
                ("Kunyit", ["Lokal", "Madura", "Dong"]),
                ("Lengkuas / Laos", ["Lokal"]),
                ("Serai / Sereh", ["Lokal"]),
                ("Kemangi", ["Lokal"]),
                ("Daun Salam", ["Basah", "Kering"]),
                ("Daun Jeruk", ["Segar", "Kering"]),
                ("Tauge / Kecambah", ["Kacang Hijau", "Kedelai"]),
                ("Pakis / Paku", ["Lokal"]),
                ("Genjer", ["Lokal"]),
                ("Kepput Lanjar / Talas", ["Lokal"]),
                ("Ubi Jalar", ["Cilembu", "Orange", "Ungu", "Lokal"]),
                ("Ubi Kayu / Singkong", ["Lokal", "Mentega"]),
            ],
            "Buah-buahan": [
                ("Pisang", ["Ambon", "Barang", "Kepok/Kepis", "Raja", "Mas/Kirip", "Susu"]),
                ("Mangga", ["Arummanis", "Gedong", "Harummanis Kuning", "Manalagi", "Okayongo", "Apple Mango"]),
                ("Jeruk", ["Siem", "Pontianak", "Medan/Golden", "Jepang/Mikan", "Lemon", "Nipis", "Pamelo/Bali"]),
                ("Semangka", ["Inul/Hijau Gelap", "Yellow/Kuning", "Seedless", "Watermelon Lokal"]),
                ("Melon", ["Inul", "Golden/Honeydew", "Rockmelon", "Zamrock"]),
                ("Nanas", ["Madu", "Bogor", "Palembang", "Hias"]),
                ("Pepaya", ["California", "IPB 9", "Bangkok", "Exotic"]),
                ("Buah Naga", ["Merah", "Putih", "Kuning/Gold"]),
                ("Alpukat", ["Mentega", "Alpukat Local", "Kepe", "Rawa"]),
                ("Durian", ["Musang King", "Montong", "Bawor", "Sunan", "D24", "Petrok", "Sancaka", "Medan/Omni"]),
                ("Manggis", ["Lokal", "Kalimantan"]),
                ("Rambutan", ["Binjai", "Lebak-Buksus", "Aceh", "Rapiah"]),
                ("Lengkeng", ["Diamond River", "Kristal", "Pingpong", "Itoh"]),
                ("Belimbing", ["Wattaka/Dewi", "Lokal", "Manis"]),
                ("Apel", ["Malang", "Impor Rome/Washington", "Fuji"]),
                ("Anggur", ["Primbosson", "Red Globe", "Black Seedless", "Anggur Malang"]),
                ("Strawberry", ["Lokal/Fresh", "Hidroponik", "California"]),
                ("Blueberry", ["Impor", "Hidroponik Lokal"]),
                ("Kiwi", ["Green", "Gold", "Impor"]),
                ("Markisa", ["Ungu", "Kuning/Pasiflora"]),
                ("Sirsak", ["Lokal"]),
                ("Jambu Biji", ["Kristal", "Getas/Amerika", "Lokal Merah", "Bangkok"]),
                ("Jambu Air", ["Beli Madu", "Crispy", "King Rose", "Sirat"]),
                ("Salak", ["Pondoh", "Bali", "Sugar", "Mini"]),
                ("Kesemek", ["Fuyu", "Impor"]),
                ("Cempedak", ["Lokal"]),
                ("Nangka / Gori", ["Lokal", "Terseno", "Bulu"]),
                ("Kedondong", ["Lokal"]),
                ("Sawo", ["Lokal", "Manila"]),
                ("Menteng / Kepundung", ["Lokal"]),
                ("Kurma", ["Medjool", "Ajwa", "Sukari", "Lokal"]),
                ("Delima", ["Merah", "Impor"]),
                ("Avocado Lokal", ["Alpukat Mentega Lokal"]),
                ("Pir", ["Lokal", "Impor"]),
                ("Plum", ["Impor"]),
                ("Persik / Peach", ["Impor", "Lokal"]),
                ("Aprikot", ["Impor"]),
                ("Cherry", ["Impor"]),
                ("Lychee / Leci", ["Impor", "Lokal"]),
                ("Longan", ["Impor"]),
                ("Dragon Fruit Hybrid", ["Cross-pollinated"]),
                ("Camellia / Buah Kertas", ["Lokal"]),
            ],
        },
    },
    "Perkebunan": {
        "subkategori": ["Tanaman Tahunan", "Tanaman Industri", "Rempah Perkebunan", "Karet & Getah", "Serat & Lainnya"],
        "produk": {
            "Tanaman Tahunan": [
                ("Kopi", ["Arabika Gayo", "Robusta Lampung", "Toraja", "Kintamani", "Java Preanger", "Fine Robusta"]),
                ("Kakao / Cacao", ["Fermentasi", "Non-Fermentasi", "Butter Kakao", "Powder"]),
                ("Teh", ["Hitam", "Green Tea", "Oolong", "White Tea", "Teh Malabar", "Teh Java"]),
                ("Karet", ["RSS 1-5", "Crumb Rubber SIR", "Lateks", "Slab"]),
                ("Kina", ["Cinchuda Bark", "Quinine Sulfate"]),
                ("Kapas", ["Lintas", "Benih Kapas"]),
            ],
            "Tanaman Industri": [
                ("Sawit / Kelapa Sawit", ["TBS/Fresh Fruit Bunch", "CPO", "PKO", "Bibit Sawit"]),
                ("Kelapa", ["Butiran", "Desicated", "Minyak Kelapa/VCO", "Serbuk Sabut", "Coir", "Batok Arang"]),
                ("Tebu", ["Gula Kristal", "Gula Semut/Muscovado", "Molase", "Biji Tebu", "Lorok"]),
                ("Tembakau", ["Krosok", "Rajangan", "Virginiana", "Oriental", "Shreded"]),
                ("Cokelat Olahan", ["Dark Couverture", "Cocoa Nibs", "Cocoa Butter"]),
                ("Vanili", ["Vanili Planifolia", "Vanili Pod Basah", "Kering", "Powder"]),
            ],
            "Rempah Perkebunan": [
                ("Lada", ["Putih", "Hitam", "Hijau", "Lada Petaling"]),
                ("Cengkeh", ["Tangkai/Bunga Kering", "Minyak Cengkeh", "Bugil"]),
                ("Pala", ["Biji utuh", "Butter Pala", "Foil/Mace", "Minyak Pala"]),
                ("Kayu Manis", ["Kulit Kering", "Powder", "Cassia Vera", "Minyak"]),
                ("Ginger/Rimpang Ekspor", ["Jahe Emprit Bersih", "Kunyit Irisan Kering", "Lengkuas Kering"]),
                ("Kapulaga", ["Putih", "Hijau", "Black Cardamom"]),
                ("Jinten", ["Putih", "Hitam"]),
                ("Adas / Fennel", ["Biji Adas", "Minyak Adas"]),
                ("Kemiri", ["Utuh", "Kernel"]),
                ("Andaliman", ["Merica Batak"]),
            ],
            "Serat & Lainnya": [
                ("Rosella / Kenaf", ["Serat Kering", "Biji Rosella"]),
                ("Yute/Jute", ["Serat mentah"]),
                ("Abaca / Manila Hemp", ["Serat"]),
                ("Bambu", ["Zen", "Bambu Olahan", "Tali Bambu"]),
                ("Rotan", ["Rotan Segar", "Asli", "Sikat/Pole"]),
                ("Porang / Konjac", ["Umbi Segar", "Chips", "Tepung Konjac"]),
                ("Menthol/Camphor", ["Minyak Kamper", "Kristal Menthol"]),
                ("Nilam", ["Minyak Nilam/Patchouli Oil"]),
                ("Sereh Wangi", ["Minyak Citronella", "Daun Kering"]),
                ("Gaharu", ["Gaharu Mutu Super", "Serbuk Gaharu"]),
                ("Arenga / Enau", ["Gula Aren", "Nira", "Biji Kolang-Kaling"]),
                ("Lontar/Siwalan", ["Gula Lontar", "Buah Lontar"]),
                ("Nira Kelapa / Gula Kelapa", ["Cetak", "Serbuk"]),
                ("Sagu", ["Tepung Sagu", "Sagu Batang"]),
            ],
        },
    },
    "Perikanan": {
        "subkategori": ["Air Tawar", "Air Laut"],
        "produk": {
            "Air Tawar": [
                ("Lele", ["Sanggkuriang", "Dumbo/Mutiara", "Kumbia", "Fillet Lele", "Lele Asap"]),
                ("Nila / Mujair", ["Nila Gift", "Nila Gesit", "Mujair Lokal", "Fillet Nila", "Nila Merah"]),
                ("Mas", ["Mas Lokan", "Mas Majapahit", "Mas Jayagiri", "Koi Konsumsi", "Ikan Mas Asin"]),
                ("Patin", ["Patin Lokal", "Pangasius/Patin Fillet", "Patin Dumbo"]),
                ("Gurame", ["Gurame Sagu", "Gurame Pahat", "Gurame Majalaya", "Anakan Gurame"]),
                ("Bandeng", ["Bandeng Lokal", "Bandeng Rajdanmas", "Bandeng Presto"]),
                ("Carp / Ikan Mas Koki", ["Hias Konsumsi"]),
                ("Belida / Sepat Siama", ["Lokal", "Fillet Belida"]),
                ("Baung", ["Baung Sangkuriang", "Baung Kalapan"]),
                ("Sepat", ["Sepat Soso", "Sepat Lokal"]),
                ("Tawes", ["Tawes Lokal", "Tawes Merah"]),
                ("Bawal Air Tawar", ["Pacu", "Hitam"]),
                ("Hampala / Papuyu", ["Lokal"]),
                ("Tombro / Rasbora", ["Konsumsi Kecil"]),
                ("Wader", ["Wader Kuning", "Wador/local"]),
                ("Betutu / Butana", ["Lokal"]),
                ("Udang Vaname (Tambak Air Payau)", ["Benur", "Udang Hidup", "Beku"]),
                ("Udang Galah", ["Besar", "Medium", "Fresh Air Tawar"]),
                ("Lobster Air Tawar", ["Red Claw", "Procambarus"]),
                ("Kepiting Soka / Bakau", ["Softshell", "Cacing"]),
                ("Cepat / Keong Emas", ["Keong Slice"]),
                ("Ikan Gabus / Senapan", ["Fresh", "Kerupuk"]),
                ("Toman / Gabus", ["Fresh", "Asin"]),
                ("Pregolan / Sebelat", ["Lokal"]),
                ("Lelea / Betok", ["Konsumsi lokal"]),
                ("Ikan Patin Hybrid", ["Benih", "Konsumsi"]),
                ("Cilia / Cicilia", ["Lokal"]),
                ("Tambakan / Tambra", ["Lokal"]),
                ("Buntal Air Tawar", ["Ikan Setan/Tetraodon"]),
                ("Algae / Rumput Air Tawar", ["Spirulina", "Chlorella"]),
                ("Benih Ikan Air Tawar", ["Lele", "Nila", "Mas", "Gurame", "Patin", "Bandeng"]),
            ],
            "Air Laut": [
                ("Tuna", ["Tongkol", "Madidihang/Yellowfin", "Sirip Kuning", "Looseley", "Tuna Matsumoto", "Cakalang"]),
                ("Kakap", ["Kakap Merah", "Kakap Putih", "Kakap Snapper"]),
                ("Baramundi / Barramundi", ["Budidaya Laut", "Fresh"]),
                ("Kerapu", ["Kerapu Macan", "Kerapu Cantang", "Kerapu Tikua", "Kerapu Sunu"]),
                ("Snapper / Kuniran", ["Lokal"]),
                ("Tenggiri", ["Tenggiri Fresh", "Suwir", "Bakwan"]),
                ("Kurisi / Cakalang", ["Fresg", "Asap", "Cincang"]),
                ("Selar", ["Kuning", "Bento/Bandeng Laut"]),
                ("Kuniran / Kuwe", ["Fresh"]),
                ("Bawal Laut", ["Bawal Hitam", "Bawal Es"]),
                ("Ikan Teri / Anchovy", ["Teri Medan", "Teri Jambal", "Tubuk", "Kering"]),
                ("Sarden", ["Sarden Segar", "Fillet"]),
                ("Mackerel / Kembung", ["Kembung Fire", "Kembung Etong", "Herring"]),
                ("Tongkol", ["Tongkol Ekor Kuning", "Tongkol Abu-abu"]),
                ("Cumi-cumi", ["Cumi Besar", "Cumi Sotong", "Cumi Asin", "Ring Cumi Beku"]),
                ("Kepiting", ["Kepiting Bakau/Soka", "Rajungan", "Kepiting Raja/Ranitun"]),
                ("Udang Windu", ["Vaname Laut", "Udang Dogol", "Udang Jeruk", "Udang Barong"]),
                ("Lobster", ["Pasir/Bamboo Lobster", "Mutiaral", "Rock Lobster", "Lobster Live"]),
                ("Kerang", ["Kerang Dara", "Kerang Hijau/Green Mussel", "Kipas-kipas", "Tiram/Oyster"]),
                ("Rumput Laut", ["Eucheuma Cottonii", "Gracilaria", "Sargassum", "Nori"]),
                ("Ikan Terbang / Tobiko", ["Flying Fish", "Telur Terbang"]),
                ("Marlin / Tombak", ["Tombak Bisapan", "Marlin"]),
                ("Swordfish / Layaran", ["Ikan Layaran"]),
                ("Mahi-mahi / Dencugi", ["Dencus/Dolphin Fish"]),
                ("Wahoo / Aruto", ["Fast swimming mackerel"]),
                ("Ekor Kuning", ["Yellowtail Scad"]),
                ("Julung-julung", ["Needle Fish"]),
                ("Belanak Laut / Mullet", ["Mugil", "Kakap Merlang"]),
                ("Parrotfish / Ikan Kakatua", ["Lokal"]),
                ("Rabbitfish / Sumpil", ["Sumpil Dua Tonjong"]),
                ("Napoleon / Kerapu Napoleon", ["Budidaya Karamba"]),
                ("Abalone / Siput Laut", ["Budidaya"]),
                ("Teripang / Sea Cucumber", ["Kering", "Segar"]),
                ("Kuda Laut", ["Kering Legal Budidaya"]),
                ("Ikan Bulan / Moonfish", ["Lokal"]),
                ("Selar Kuning", ["Ikan Bento"]),
                ("Tuna Mata Besar", ["Bigeye"]),
                ("Spanish Mackerel / Alu-alu", ["Lokal"]),
                ("Kwe / Kuwe", ["Kuwe Lengis"]),
                ("Grouper Hybrid", ["Kerapu Hybrid Cantang x Kertang"]),
                ("Kertang / Giant Grouper", ["Budidaya Karamba"]),
                ("Sarden Laut Dalam", ["Ikan Layang"]),
                ("Tenggiri Sirip", ["Small Tunny"]),
            ],
        },
    },
    "Peternakan": {
        "subkategori": ["Sapi & Kerbau", "Kambing & Domba", "Unggas", "Babi", "Perah Susu", "Lainnya"],
        "produk": {
            "Sapi & Kerbau": [
                ("Sapi Potong", ["Limousin", "Simmental", "Brangman/Angus", "Sapi Bali", "Sapi Madura", "Peranakan Ongole (PO)", "Charolais", "Highgrade IB"]),
                ("Sapi Bakalan", ["Bakalan Jantan", "Bakalan Betina", "Feedlot"]),
                ("Kerbau", ["Kerbau Lumpur", "Kerbau Sungai", "Murrah"]),
                ("Sapi Perah", ["FH/Fries Holland", "Cross FH", "Sapi Jersey"]),
                ("Bibit Ternak Sapi", ["Calon Indukan", "Pedet", "Bibit IB/Semen"]),
                ("Hijauan Pakan", ["Rumput Odot", "Indigofera", "Napas/Table", "Silase Jagung", "Hay Alfalfa"]),
            ],
            "Kambing & Domba": [
                ("Kambing PE", ["PE 76", "PE Prima", "Kambing Jawa Randu"]),
                ("Kambing Etawa", ["Etawa Senduro", "Etawa Cross", "PE-Etawa"]),
                ("Kambing Kacang", ["Kacang Lokal", "Kacang Kalimantan"]),
                ("Kambing Boer", ["Fullblood", "Boer Cross"]),
                ("Kambing Gembrong", ["Bali"]),
                ("Domba Ekor Tipis", ["Garut", "Local"]),
                ("Domba Ekor Gemuk", ["Tule/Tail Fat", "Damascus"]),
                ("Domba Merino", ["Merino Cross"]),
                ("Domba Batur", ["Wonosobo"]),
                ("Domba Dorper", ["Dorper White"]),
                ("Kambing Peranakan Boer", ["Kalista", "PB 050"]),
                ("Susu Kambing Etawa", ["Fresh", "Pasteurisasi", "Bubuk"]),
            ],
            "Unggas": [
                ("Ayam Broiler", ["Frozen Karkas", "Live Bird", "Fillet dada", "Paha", "Carcass Grade A"]),
                ("Ayam Kampung", ["Kampung Super", "Kampung Asli/Jawa", "Kampung KUB", "Sentul", "Nstradburg/KUD"]),
                ("Ayam Petelur", ["Layer Afkir", "DOC Layer", "Pullet"]),
                ("Bebek / Itik", ["Itik Alabio", "Bali Mojosari", "Itik Peking", "Bebek Pedaging", "Telur Bebek Asin"]),
                ("Mentok / Muscovy", ["Blaster", "Hypokokus"]),
                ("Puyuh", ["Burung Puyuh Petelur", "Puyuh Pedaging", "Telur Puyuh"]),
                ("Angsa", ["Angsa Batu", "Angsa Graylag", "Foie Gras Legal"]),
                ("Kalkun", ["Turkey Bronze", "Kalkun Lokal"]),
                ("Burung Kicau & Hias", ["Kenari", "Cendet", "Pleci", "Skopsi", "Pentet", "Murai Batu", "Anis Kuning", "Cucak Ijo", "Trucuk", "Kacer", "Jalak", "Parkit", "Cockatiel", "Budgerigar", "Lovebird", "Zebra Finch"]),
                ("DOC & Bibit Unggas", ["DOC Broiler", "DOC Layer", "PDOC Bebek", "Day Old Quail"]),
                ("Pakan Unggas", ["MIX Konsentrat", "Bekatil", "Corn Flake", "Sorgum Pakan"]),
                ("Hasil Turunan", ["Telur Ayam Negeri", "Telur Ayam Kampung", "Telur Bebek", "Madu Trigona dari Peternakan"]),
            ],
            "Babi": [
                ("Babi Hidup NON HALAL", ["Landrace", "Large White/Yorkshire", "Duroc", "Hampshire", "Babi Bali", "CEB/Kampret", "Cross F1", "Bibit Bakalan Babi"]),
                ("Daging Babi NON HALAL", ["Pork Belly/Samcan", "Bacon", "Ham", "Shoulder/Schalde", "Loin/Tenderloin", "Ribs/Iga", "Kakiba", "Ear/Buntut", "Jeroan", "Ground Pork"]),
                ("Olahan Babi NON HALAL", ["Sosis Babi", "Bak Siong", "Siobak/Bakso Babi", "Dendeng Babi", "Pig Skin/Kulit", "Lard/Minyak Babi", "Ham Smoked"]),
                ("Produk Turunan Babi", ["Gelatin Food Grade", "Enzim Pankreatin", "Kolagen Babi", "Bratwurst"]),
            ],
            "Perah Susu": [
                ("Sapi Perah FH", ["Primadona", "Heifer"]),
                ("Kambing Perah Etawa", ["Peranakan Etawa dara", "Etawa Pure"]),
            ],
            "Lainnya": [
                ("Kelinci", ["New Zealand White", "Rex", "Lop Ear", "Jawa/Kelinci Hias", "Kelinci Pedaging"]),
                ("Lebah / Madu", ["Madu Hutan", "Madu Pellegranata", "Madu Randu", "Madu Klanceng/Trigona", "Royal Jelly", "Propolis", "Bee Pollen", "Lilin Lebah"]),
                ("Cacing Sutera / Ulat", ["Ulat Hongse/Ulat Jerman", "Maggot BSF", "Cacing Tanah", "Cacing sutera"]),
                ("Serikon / Landak", ["Landak Mini Baldwin", "Landak Jamaican", "Landak Jawa"]),
                ("Budadaya Serbaguna", ["Sarang Burung Walet"]),
                ("Pakan Ternak Umum", ["Dedak/Bekatil", "Ampas Tahu", "Ampas Kelapa", "Pollard Gandum", "Bungkil Kedelai", "CPO Feed"]),
                ("Obat & Vitamin Ternak", ["Vitamin Mix", "Probiotik", "Antiparasit Legal"]),
                ("Peralatan Kandang", ["Feeder", "Drinker", "Kawat Ternak", "Tali Halter"]),
            ],
        },
    },
}

# Label khusus untuk menandai produk Non Halal
NON_HALAL_LABEL = "Non Halal"


def flatten_products():
    """Kembalikan list (kategori, subkategori, produk, jenis_list) untuk seed DB."""
    rows = []
    for kat, data in MASTER_PRODUK.items():
        for sub, prods in data["produk"].items():
            for nama, jenis in prods:
                if not nama or not isinstance(nama, str):
                    continue
                non_halal = NON_HALAL_LABEL in nama
                rows.append({
                    "kategori": kat,
                    "subkategori": sub,
                    "nama_produk": nama.replace(" NON HALAL", "").replace(" NON-HALAL", ""),
                    "jenis": ", ".join(jenis) if jenis else "",
                    "non_halal": non_halal,
                })
    return rows


if __name__ == "__main__":
    n = 0
    for r in flatten_products():
        n += 1
    print("Total produk:", n)
